version: '3.3'

services:
  java_server:
    container_name: java_server
    build: .
    # volumes:
    #   - '.:/app'
    #   - '/app/node_modules'
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=development
